spring:
  config:
    activate:
      on-profile: prod

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: warn
    com.mayureshpatel.pfdataservice: info
